title: "Beyond the Rift"
author: "Dee Pennyway"
logo: "banner.png"
logowhite: "banner.png"
favicon: "favicon.png"
googlefonts:
    title: "Oswald"
    heading: "Crimson Pro"
    body: "Crimson Pro"
    sidebar: "Crimson Pro"
    dropcap: "Yanone Kaffeesatz"
style:
    accent: "#e9a563"
    sidebartext: "#efefef"
    sidebarback: "var(--accent)"
    paperbg: "#444"
    paper: "paper-black.png"
    cover: "paper-dark.png"
    coveraccent: "#e9a563"
    coverbg: "#39483e"
    sidebartexture: "paper-black.png"
    bodycolor: "#efefef"
    velvet: "burlwood.png"
    texture: "diamonds.png"
    bgaccent: "#ddd"
    background: "water.jpg"